
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(808, 623)
        Form.setStyleSheet("background-color: #F4F0F8")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(200, 170, 381, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.num_of_X_wins = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.num_of_X_wins.setFont(font)
        self.num_of_X_wins.setStyleSheet("background-color: white;")
        self.num_of_X_wins.setObjectName("num_of_X_wins")
        self.gridLayout.addWidget(self.num_of_X_wins, 1, 1, 1, 1)
        self.num_of_games_played = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.num_of_games_played.setFont(font)
        self.num_of_games_played.setStyleSheet("background-color: white;")
        self.num_of_games_played.setObjectName("num_of_games_played")
        self.gridLayout.addWidget(self.num_of_games_played, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: #FFD050;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: #FFD050;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: #FFD050;")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.num_of_O_wins = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.num_of_O_wins.setFont(font)
        self.num_of_O_wins.setStyleSheet("background-color: white;")
        self.num_of_O_wins.setObjectName("num_of_O_wins")
        self.gridLayout.addWidget(self.num_of_O_wins, 2, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Статистика"))
        self.num_of_X_wins.setText(_translate("Form", "0"))
        self.num_of_games_played.setText(_translate("Form", "0"))
        self.label.setText(_translate("Form", "Всего сыграно игр:"))
        self.label_3.setText(_translate("Form", "Количество побед X:"))
        self.label_5.setText(_translate("Form", "Количество побед O:"))
        self.num_of_O_wins.setText(_translate("Form", "0"))
